language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcurl4-openssl-dev libssl-dev
install: "pip install -r requirements.txt"
script:
  - flake8 arm
